site_name: VTKExamples
theme: material
site_url: https://lorensen.github.io/VTKExamples/site/
site_favicon: 'images/favicon.ico'
repo_name: lorensen/VTKExamples
repo_url: https://github.com/lorensen/VTKExamples
theme_dir: custom_theme
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
google_analytics:
  -  'UA-3660134-4'
  -  'auto'
extra_css:
  -  'stylesheets/extra.css'
